#!/bin/bash

python3 -m pip install lxml requests fuzzywuzzy pandas
rm -rf /usr/local/share/nyaabag
rm -rf /usr/local/bin/nyaabag
cp -r usr/local/share/nyaabag /usr/local/share/nyaabag
cp -r usr/local/bin/nyaabag /usr/local/bin/nyaabag